# Generated by Django 3.1.7 on 2021-03-19 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('assetId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assetName', models.CharField(max_length=200, null=True)),
                ('assetTypeId', models.IntegerField(null=True)),
                ('listingType', models.CharField(max_length=60, null=True)),
                ('propertyType', models.CharField(max_length=60, null=True)),
                ('legalTypeId', models.SmallIntegerField(null=True)),
                ('tokenId', models.CharField(max_length=60, null=True)),
                ('parcelId', models.CharField(max_length=60, null=True)),
                ('streetAddress', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=60, null=True)),
                ('state', models.CharField(max_length=60, null=True)),
                ('zipCode', models.CharField(max_length=10, null=True)),
                ('price', models.IntegerField(null=True)),
                ('funded', models.IntegerField(null=True)),
                ('forcastedIncome', models.IntegerField(null=True)),
                ('minInvestment', models.IntegerField(null=True)),
                ('maxInvestment', models.IntegerField(null=True)),
                ('share', models.IntegerField(null=True)),
                ('yearBuilt', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=60, null=True)),
                ('acerage', models.FloatField(max_length=60, null=True)),
                ('llc', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('investorTypeId', models.SmallIntegerField()),
                ('kycVerified', models.BooleanField()),
                ('walletAddress', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('avaxusername', models.CharField(max_length=30)),
                ('avaxpassword', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('txId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txTypeId', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('txNFTId', models.CharField(max_length=200)),
                ('txAvaxId', models.CharField(max_length=200)),
                ('txDateTime', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.asset', verbose_name='Asset')),
            ],
            options={
                'ordering': ['-txDateTime'],
            },
        ),
    ]
