# Generated by Django 3.1.7 on 2021-03-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetId', models.UUIDField()),
                ('assetName', models.CharField(max_length=200)),
                ('assetTypeId', models.IntegerField()),
                ('opportunityType', models.CharField(max_length=60)),
                ('legalTypeId', models.SmallIntegerField()),
                ('tokenId', models.CharField(max_length=60)),
                ('parcelId', models.CharField(max_length=60)),
                ('streetAddress', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('zipCode', models.IntegerField()),
                ('country', models.CharField(max_length=60)),
                ('acerage', models.FloatField(max_length=60)),
                ('llc', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.UUIDField()),
                ('fullName', models.CharField(max_length=100)),
                ('investorTypeId', models.SmallIntegerField()),
                ('kycVerified', models.BooleanField()),
                ('walletAddress', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
