# Generated by Django 3.1.7 on 2021-03-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
        migrations.AddField(
            model_name='asset',
            name='details',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='listedrice',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='originalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='tokenNumber',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='forcastedIncome',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
    ]
