# Generated by Django 3.1.6 on 2021-03-26 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210320_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='tokenId',
            new_name='avalancheAssetId',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='listedrice',
            new_name='listedPrice',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='originalPrice',
            new_name='purchasedPrice',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='realiumUserId',
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetId',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txTypeId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avaxpassword',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avaxusername',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='walletAddress',
            field=models.CharField(max_length=60),
        ),
    ]
