# Generated by Django 3.1.7 on 2021-03-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210304_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='opportunityType',
        ),
        migrations.AddField(
            model_name='asset',
            name='forcastedIncome',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='funded',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='listingType',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maxInvestment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='minInvestment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='propertyType',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='share',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='yearBuilt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='acerage',
            field=models.FloatField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assetTypeId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='country',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='legalTypeId',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='llc',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='parcelId',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='state',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='streetAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tokenId',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='zipCode',
            field=models.IntegerField(null=True),
        ),
    ]
