# Generated by Django 3.1.6 on 2021-03-26 03:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210326_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
