# Generated by Django 3.1.7 on 2021-03-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210305_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='zipCode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=200, null=True)),
                ('transactionTypeId', models.IntegerField()),
                ('transactionHash', models.CharField(max_length=200, null=True)),
                ('hashVersion', models.IntegerField()),
                ('transactionDateTime', models.DateTimeField(null=True)),
                ('assetId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.asset', verbose_name='Asset')),
            ],
        ),
    ]
