# Generated by Django 3.1.7 on 2021-03-17 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210312_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-txDateTime']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionAvaxId',
            new_name='txAvaxId',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionNFTId',
            new_name='txNFTId',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionTypeId',
            new_name='txTypeId',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transactionDateTime',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transactionId',
        ),
        migrations.AddField(
            model_name='transaction',
            name='txDateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='txId',
            field=models.CharField(default='78370756368506183920', editable=False, max_length=20, unique=True),
        ),
    ]
