# Generated by Django 3.1.7 on 2021-03-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210317_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txId',
            field=models.CharField(default='57780973194506454393', editable=False, max_length=20, unique=True),
        ),
    ]
